[package]
name = "fd"
version = "0.1.0"
authors = ["Nextensio <team@nextensio.net>"]
edition = "2018"

[dependencies]
libc = {version = "0.2"}
mio = {version = "0.7", features = ["os-poll", "net", "os-util"]}
common = { path = "../../common" }
